#
# Common configuration for each firstwiki repo
#

permalink:        pretty

exclude: [vendor, script]

gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-github-metadata
  
author:
  name:           FIRSTWiki Contributors
  url:            http://howeverina.github.io
  email:

# Setup
title:            연이나위키
tagline:          이것저것 정리하는 개인 위키
paginate:         5
safe:             false
excerpt_separator: ""
strict_front_matter: true

# source: .
#data_dir:         _common/_data
#includes_dir:     _common/_includes
#layouts_dir:      _common/_layouts

#
# Begin specific configuration for this repo
#

url:              http://howeverina.github.io
baseurl:          /wiki

collections:
  main: 
    output: true
    permalink: /:slug
  music:
    output: true
    permalink: /:slug
  gugak:
    output: true
    permalink: /:slug
  earlyjs:
    output: true
    permalink: /:slug
  humanities:
    output: true
    permalink: /:slug

#
# Defaults to make it easy to contribute new content
#

defaults:
  - 
    scope:
      path: ""
      type: "main"
    values:
      layout: page
  - 
    scope:
      path: ""
      type: "music"
    values:
      layout: page
  - 
    scope:
      path: ""
      type: "gugak"
    values:
      layout: page
  - 
    scope:
      path: ""
      type: "earlyjs"
    values:
      layout: page
  - 
    scope:
      path: ""
      type: "humanities"
    values:
      layout: page
